path: /bolt/service/test/config
parameters:
  phone:
    value: '2324'
    label: 'Номер телефона'
  vk:
    value: 'http://vk.com'
    label: Вконтакте
    required: false
  fix_close:
    type: textarea
    value: 'Выполнен - заказ выдан клиенту'
    label: 'Текст для заказов на ремонт: выполнен'
