path: /bolt/service/test/config
parameters:
  google:
    value: 'http://google.com'
    label: Google+
  twitter:
    value: 'http://twitter.com'
    label: Twitter
  make_accept:
    value: 'Принят - Ваш заказ комплектуется линзами и готовится к передаче в мастерскую'
    label: 'Текст для заказов на изготовление: принят'
    type: textarea
